In [1]:
import tensorflow as tf
print("Version of tensorflow is : ",tf.__version__)

Version of tensorflow is :  2.1.0


In [50]:
#variable
#==================
string = tf.Variable("It is my string",tf.string)
intVar = tf.Variable(5,tf.int64)
floating = tf.Variable(35.5,tf.float64)

In [5]:
print("String Variable is : ",string)

String Variable is :  <tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'It is my string'>


In [6]:
print("Value of string Variable is : ",string.numpy())

Value of string Variable is :  b'It is my string'


In [16]:
print("Rank details := ",tf.rank(string))

Rank details :=  tf.Tensor(0, shape=(), dtype=int32)


In [17]:
print("Rank of string := ",tf.rank(string).numpy())

Rank of string :=  0


In [10]:
print("Value of int variable is := ",intVar.numpy())
print("Value of float variable is := ",floating.numpy())

Value of int variable is :=  5
Value of float variable is :=  35.5


In [14]:
print("Name of float variable := ",floating.name)

Name of float variable :=  Variable:0


In [18]:
#Different Tensor

In [26]:
vector_1 = tf.zeros((5))
print("Vector_1 := ",vector_1.numpy())
print("Rank := ",tf.rank(vector_1).numpy())
print("=============================")
vector_1 = tf.reshape(vector_1,(5,-1))
print("Vector_1 := ",vector_1.numpy())
print("Rank := ",tf.rank(vector_1).numpy())
print("=============================")
vector_1 = tf.reshape(vector_1,(-1,5))
print("Vector_1 := ",vector_1.numpy())
print("Rank := ",tf.rank(vector_1).numpy())

Vector_1 :=  [0. 0. 0. 0. 0.]
Rank :=  1
Vector_1 :=  [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Rank :=  2
Vector_1 :=  [[0. 0. 0. 0. 0.]]
Rank :=  2


In [27]:
vector_2 = tf.ones((2,3))
print("Vector_2 := ",vector_2.numpy())
print("Rank := ",tf.rank(vector_2).numpy())
print("=============================")
vector_2 = tf.reshape(vector_2,(1,3,-1))
print("Vector_2 := ",vector_1.numpy())
print("Rank := ",tf.rank(vector_1).numpy())
print("=============================")
vector_2 = tf.reshape(vector_2,(3,1,-1))
print("Vector_2 := ",vector_2.numpy())
print("Rank := ",tf.rank(vector_2).numpy())

Vector_2 :=  [[1. 1. 1.]
 [1. 1. 1.]]
Rank :=  2
Vector_2 :=  [[0. 0. 0. 0. 0.]]
Rank :=  2
Vector_2 :=  [[[1. 1.]]

 [[1. 1.]]

 [[1. 1.]]]
Rank :=  3


In [30]:
print("Shape of vector_2 := ",vector_2.shape)

Shape of vector_2 :=  (3, 1, 2)


In [35]:
vector_3 = tf.Variable(tf.ones((3,3),tf.float64))

In [46]:
vector_3[1,1].numpy()

1.0

In [55]:
print(string.numpy())

b'It is my string'
